version: '3.9'

services:
  #new service (java_app)
  api:
    container_name: api
    image: rest-api/api:1.0.0
    build: .
    ports:
      - 9090:8080
    environment:
      - DATABASE_URL=jdbc:postgresql://java_db:5432/postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
    depends_on:
      - postgress-db

  #old service (postgres)
  postgress-db:
    container_name: postgress-db
    image: postgres:12
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 32443244
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}